### ISSUE TITLE
Building for the 64-bit system

### ISSUE THREAD

**Issue by egorsmkv** [sloonz/cfeedparser#1]
To assemble the need to use this path to the library:

```
/usr/lib/x86_64-linux-gnu/glib-2.0/include
```

**Comment by sloonz** [comment]
Should be fixed by last commit, could you try again ?

**Comment by egorsmkv** [comment]
@sloonz You mean my commits here: https://github.com/eg0r/cfeedparser?

**Comment by sloonz** [comment]
No, I mean https://github.com/sloonz/cfeedparser/commit/cb16022343bed23f9d16584be49b0e2fdaf5b6fc

**Comment by egorsmkv** [comment]
Checked. Are you fine.
